[package]
name = "janus"
version = "0.1.7"
edition = "2021"
authors = ["Xqhare"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5"
